export const weatherIcons = {
  "01d": "./images/weather-icon/clear-sky.svg",     // Céu limpo (dia)
  "01n": "./images/weather-icon/clear-sky-night.svg",   // Céu limpo (noite)
  "02d": "./images/weather-icon/few-clouds.svg",  // Parcialmente nublado (dia)
  "02n": "./images/weather-icon/few-clouds-night.svg", // Parcialmente nublado (noite)
  "03d": "./images/weather-icon/scattered-clouds.svg",    // Nublado (dia)
  "03n": "./images/weather-icon/scattered-clouds-night.svg",  // Nublado (noite)
  "04d": "./images/weather-icon/broken-clouds.svg",  // Nuvens quebradas (dia)
  "04n": "./images/weather-icon/broken-clouds-night.svg", // Nuvens quebradas (noite)
  "09d": "./images/weather-icon/shower-rain.svg",     // Chuva leve (dia)
  "09n": "./images/weather-icon/shower-rain-night.svg",   // Chuva leve (noite)
  "10d": "./images/weather-icon/rain.svg",    // Chuva com sol (dia)
  "10n": "./images/weather-icon/rain-night.svg",  // Chuva com lua (noite)
  "11d": "./images/weather-icon/thunderstorm.svg",   // Tempestade (dia)
  "11n": "./images/weather-icon/thunderstorm-night.svg", // Tempestade (noite)
  "13d": "./images/weather-icon/snow.svg",      // Neve (dia)
  "13n": "./images/weather-icon/snow-night.svg",    // Neve (noite)
  "50d": "./images/weather-icon/mist.svg",      // Névoa (dia)
  "50n": "./images/weather-icon/mist-night.svg"     // Névoa (noite)
};